# Generated by Django 3.2.14 on 2022-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
