# Generated by Django 3.2.14 on 2022-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('owner_status', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
    ]
